config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('jet/', include('jet.urls', namespace="jet")),
    path('jet/dashboard/', include('jet.dashboard.urls', namespace="jet-dashboard")),
    path(settings.ADMIN_URL, admin.site.urls),
    path('account/', include('main.users.urls', namespace="users")),
    path('api/', include('main.api.urls', namespace="api")),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('main.web.urls', namespace="web")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path(route='profile/', view=profile_view, name='profile_view'),
    path(route='settings/', view=settings_view, name='settings_view'),
    path(route='activity_log/', view=activity_log_view, name='activity_log_view'),
    path(route='login/', view=signin_view, name="signin_view"),
    path(route='logout/', view=logout_view, name="logout_view"),
    path(route='verify-email/<str:uidb64>/<str:token>/', view=email_verification_view, name='email_verification_view'),
    path(route='reset/<str:uidb64>/<str:token>/', view=reset_password_view, name="reset_password_view"),  # noqa
    path(route='reset/', view=reset_view, name="reset_view"),
]

main/web/urls.py
from django.urls import path

from main.web import views

app_name = 'web'

urlpatterns = [
    path('filters/manage/', views.filters_view_manage, name='filters_view_manage'),
    path('filters/', views.filters_view, name='filters_view'),
    path('groups/manage/', views.groups_view_manage, name='groups_view_manage'),
    path('groups/', views.groups_view, name='groups_view'),
    path('httpccm/manage/', views.httpccm_view_manage, name='httpccm_view_manage'),
    path('httpccm/', views.httpccm_view, name='httpccm_view'),
    path('morouter/manage/', views.morouter_view_manage, name='morouter_view_manage'),
    path('morouter/', views.morouter_view, name='morouter_view'),
    path('mtrouter/manage/', views.mtrouter_view_manage, name='mtrouter_view_manage'),
    path('mtrouter/', views.mtrouter_view, name='mtrouter_view'),
    path('smppccm/manage/', views.smppccm_view_manage, name='smppccm_view_manage'),
    path('smppccm/', views.smppccm_view, name='smppccm_view'),
    path('send_message/manage/', views.send_message_view_manage, name='send_message_view_manage'),
    path('send_message/', views.send_message_view, name='send_message_view'),
    path('submit_logs/export/', views.submit_logs_export, name='submit_logs_export'),
    path('submit_logs/export/progress/<str:task_id>/', views.submit_logs_export_progress, name='submit_logs_export_progress'),
    path('submit_logs/export/download/<str:task_id>/', views.submit_logs_export_download, name='submit_logs_export_download'),
    path('submit_logs/manage/', views.submit_logs_view_manage, name='submit_logs_view_manage'),
    path('submit_logs/', views.submit_logs_view, name='submit_logs_view'),
    path('users/manage/', views.users_view_manage, name='users_view_manage'),
    path('users/', views.users_view, name='users_view'),
    path('manage/', views.global_manage, name='global_manage'),
    path('', views.dashboard_view, name='dashboard_view'),
]

main/users/forms/signin.py
# -*- encoding: utf-8 -*-
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxLengthValidator, MinLengthValidator, EmailValidator, RegexValidator
from django import forms

class SignInForm(forms.Form):
    default_attrs = {'class': 'form-control'}
    username_validators = [
        MaxLengthValidator(limit_value=255, message=_("Maximum length allowed is %(max_length)s") % dict(max_length=255)), 
        MinLengthValidator(limit_value=2, message=_("Minimum length allowed is %(min_length)s") % dict(min_length=2)),
    ]
    password_validators = [
        MaxLengthValidator(limit_value=255, message=_("Maximum length allowed is %(max_length)s") % dict(max_length=255)), 
        # PATCH: limit_value = 1, min_length = 5
        MinLengthValidator(limit_value=1, message=_("Minimum length allowed is %(min_length)s") % dict(min_length=5)),
    ]
    username = forms.CharField(widget=forms.TextInput(
        attrs=default_attrs.update(dict(placeholder=_("Email or Username")))
    ), validators=username_validators, required=True, label=_("Email or Username"))
    password  = forms.CharField(widget=forms.PasswordInput(
        attrs=default_attrs.update(dict(placeholder=_("Password")))
    ), validators=password_validators, required=True, label=_("Password"))

main/api/views/groups.py
from django.conf import settings

from rest_framework.viewsets import ViewSet
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import status as http_status

from main.core.exceptions import MissingKeyError, ActionFailed, ObjectNotFoundError

STANDARD_PROMPT = settings.STANDARD_PROMPT
INTERACTIVE_PROMPT = settings.INTERACTIVE_PROMPT


class GroupsViewSet(ViewSet):
    """GroupsView to manage *Jasmin* user groups """
    lookup_field = 'gid'

    def list(self, request):  # noqa
        """Group List, no request parameters provided"""
        if not hasattr(request, 'telnet'):
            return Response(data={"status": "bad request"}, status=http_status.HTTP_400_BAD_REQUEST)
        telnet = request.telnet
        telnet.sendline('group -l')
        telnet.expect([r'(.+)\n' + STANDARD_PROMPT])
        result = telnet.match.group(0).strip().replace("\r", '').split("\n")
        if len(result) < 3:
            return Response(data={"groups": []}, status=http_status.HTTP_200_OK)
        groups = result[2:-2]
        return Response(data={"groups": [
            {
                'name': g.strip().lstrip('!#'),
                'status': ('disabled' if g[1] == '!' else 'enabled')
            } for g in groups if g is not None
        ]})

    def create(self, request):  # noqa
        """Create a group.
        One POST parameter required, the group identifier (a string)
        ---
        # YAML
        omit_serializer: true
        parameters:
        - name: gid
          description: Group identifier
          required: true
          type: string
          paramType: form
        """
        telnet = request.telnet
        telnet.sendline('group -a')
        telnet.expect(r'Adding a new Group(.+)\n' + INTERACTIVE_PROMPT)
        if 'gid' not in request.data:
            raise MissingKeyError('Missing gid (group identifier)')
        telnet.sendline('gid ' + request.data['gid'] + '\n')
        telnet.expect(INTERACTIVE_PROMPT)
        telnet.sendline('ok\n')

        matched_index = telnet.expect([
            r'.+Successfully added(.+)\[(.+)\][\n\r]+' + STANDARD_PROMPT,
            r'.+Error: (.+)[\n\r]+' + INTERACTIVE_PROMPT,
            r'.+(.*)(' + INTERACTIVE_PROMPT + '|' + STANDARD_PROMPT + ')',
        ])
        if matched_index == 0:
            gid = telnet.match.group(2).strip()
            telnet.sendline('persist\n')
            return Response(data={'name': gid}, status=http_status.HTTP_201_CREATED)
        else:
            raise ActionFailed(telnet.match.group(1))

    def simple_group_action(self, telnet, _action, gid):
        telnet.sendline('group -%s %s' % (_action, gid))
        matched_index = telnet.expect([
            r'.+Successfully(.+)' + STANDARD_PROMPT,
            r'.+Unknown Group: (.+)' + STANDARD_PROMPT,
            r'.+(.*)' + STANDARD_PROMPT,
        ])
        if matched_index == 0:
            telnet.sendline('persist\n')
            return Response(data={'name': gid}, status=http_status.HTTP_200_OK)
        elif matched_index == 1:
            raise ObjectNotFoundError('Unknown group: %s' % gid)
        else:
            raise ActionFailed(telnet.match.group(1))

    def destroy(self, request, gid):
        """Delete a group. One parameter required, the group identifier (a string)
        HTTP codes indicate result as follows
        - 200: successful deletion
        - 404: nonexistent group
        - 400: other error
        """
        return self.simple_group_action(request.telnet, 'r', gid)

    @action(methods=['put'], detail=True)
    def enable(self, request, gid):
        """Enable a group. One parameter required, the group identifier (a string)
        HTTP codes indicate result as follows
        - 200: successful deletion
        - 404: nonexistent group
        - 400: other error
        """
        return self.simple_group_action(request.telnet, 'e', gid)

    @action(methods=['put'], detail=True)
    def disable(self, request, gid):
        """Disable a group.
        One parameter required, the group identifier (a string)
        HTTP codes indicate result as follows
        - 200: successful deletion
        - 404: nonexistent group
        - 400: other error
        """
        return self.simple_group_action(request.telnet, 'd', gid)


groups_list = GroupsViewSet.as_view({
    'get': 'list',
    'post': 'create',
})
groups_detail = GroupsViewSet.as_view({
    'delete': 'destroy',
})
groups_enable = GroupsViewSet.as_view({'put': 'enable'})
groups_disable = GroupsViewSet.as_view({'put': 'disable'})

main/users/views/profile.py
import json
import os

from PIL import Image
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext as _

from main.core.models import ActivityLog, EmailServer
from main.core.notify import send_mail_reset_email
from main.core.utils import display_form_validations, is_json, get_query, paginate
from main.users.forms import ChangePhotoForm, ChangePasswordForm, ProfileForm
from main.users.models import User


@login_required
def profile_view(request):
    if request.POST:
        s = request.POST.get("s")
        if s == "profile":
            try:
                form = ProfileForm(request.POST)
                if form.is_valid():
                    email = request.POST.get("email") or ""
                    email = email.strip()
                    user = User.objects.get(pk=request.user.pk)
                    user.first_name = request.POST.get("first_name")
                    user.last_name = request.POST.get("last_name")
                    if email and user.email != email:
                        user.email = email
                        if EmailServer.objects.filter(active=True).exists():
                            user.is_email = False
                            send_mail_reset_email(request=request)
                            messages.info(request, _("Please check your email inbox to verify your email address"))
                    user.save()
                    messages.success(request, _("Congrats!, Your profile has been updated successfully"))
                else:
                    display_form_validations(form=form, request=request)
            except Exception as e:
                messages.error(request, _("Oops, An error occured while updating profile"))
        elif s == "avatar":
            form = ChangePhotoForm(request.POST, request.FILES)
            if form.is_valid():
                f = request.FILES.get("avatar_file")
                avatar_data = request.POST.get("avatar_data", "")
                x, y, w, h = 0.0, 0.0, 0.0, 0.0
                if is_json(avatar_data):
                    avatar_data = json.loads(avatar_data)
                    x = avatar_data.get("x")
                    y = avatar_data.get("y")
                    w = avatar_data.get("w")
                    h = avatar_data.get("h")
                fn, fx = os.path.splitext(f.name)
                img_directory = "{}/avatars/".format(settings.MEDIA_ROOT)
                if not os.path.exists(img_directory):
                    os.makedirs(img_directory)
                tmp_filename = "{}/avatars/{}_tmp{}".format(settings.MEDIA_ROOT, request.user.username, fx)
                jpg_filename = "{}/avatars/{}_tmp.jpg".format(settings.MEDIA_ROOT, request.user.username)
                with open(tmp_filename, 'wb+') as destination:
                    for chunk in f.chunks():
                        destination.write(chunk)
                im = Image.open(tmp_filename)
                im = im.convert("RGB")
                im.save(jpg_filename, "JPEG", optimize=True, quality=95)
                im = Image.open(jpg_filename)
                cropped_im = im.crop((x, y, w + x, h + y))
                cropped_im.thumbnail((512, 512), Image.ANTIALIAS)
                cropped_im.save(jpg_filename.replace("_tmp", ""), optimize=True, quality=95)
                if os.path.exists(tmp_filename):
                    os.remove(tmp_filename)
                if os.path.exists(jpg_filename):
                    os.remove(jpg_filename)
                filename = "{}avatars/{}.jpg".format(settings.MEDIA_URL, request.user.username)
                user = User.objects.filter(pk=request.user.pk).first()
                if user:
                    user.img = filename
                    user.save()
                return JsonResponse(dict(
                    message=str(_("Amazing!, Your profile picture has been updated successfully")),
                    state=200,
                    result="%(filename)s?s=%(timenow)s" % dict(filename=filename, timenow=timezone.now())
                ))
        elif s == "avatar_reset":
            try:
                user = User.objects.get(pk=request.user.pk)
                user.img = settings.DEFAULT_USER_AVATAR
                user.save()
                messages.success(request, _("OK, Your avatar profile has been reseted successfully"))
            except:
                messages.error(request, _("Oops, An error occured while removing avatar"))
        elif s == "password":
            password = request.POST.get("password")
            password1 = request.POST.get("password1")
            # password2 = request.POST.get("password2")
            form = ChangePasswordForm(request.POST)
            user = User.objects.get(pk=request.user.pk)
            if user.check_password(password):
                if form.is_valid():
                    user.set_password(password1)
                    user.save()
                    update_session_auth_hash(request, user)
                    messages.success(request, "OK, Your password has been changed successfully")
                else:
                    display_form_validations(form=form, request=request)
            else:
                messages.warning(request, "Error, Your password incorrect, please try again")
        return redirect(reverse("users:profile_view"))
    return render(request, "auth/profile.html")


@login_required
def settings_view(request):
    return render(request, "auth/settings.html")


@login_required
def activity_log_view(request):
    activitylogs = ActivityLog.objects.filter(user=request.user)
    search = request.GET.get("search")
    if search:
        entry_query = get_query(search, ("ip", "path",))
        activitylogs = activitylogs.filter(entry_query)
    activitylogs = paginate(objects=activitylogs, per_page=24, page=request.GET.get("page"))
    return render(request, "auth/activity_log.html", dict(activitylogs=activitylogs))

main/users/views/signin.py
from django.utils.translation import gettext as _
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.shortcuts import HttpResponseRedirect, render, redirect
from django.db.models import Q

from main.users.models import User
from main.users.forms import SignInForm
from main.core.utils import display_form_validations


def signin_view(request):
    form = SignInForm()
    if request.POST:
        form = SignInForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            next_page = request.POST.get("next") or "/"
            try:
                user = User.objects.get(Q(username=username) | Q(email=username))
                auth = authenticate(username=user.username, password=password)
                if auth and user:
                    if user.is_active:
                        if not user.is_email:
                            msg = _("Your Email Address is not verified yet! please verify your email address.")
                            messages.warning(request, message=msg)
                        else:
                            login(request, user)
                            return redirect(next_page)
                    else:
                        messages.warning(request, _('User banned, please contact support'))
                else:
                    raise Exception(_("Login Error, Invalid username or password, please try again"))
            except Exception as e:
                print(e)
                messages.error(request, _('Login Error, Invalid username or password, please try again'))
        else:
            display_form_validations(form=form, request=request)
    return render(request, "auth/signin.html", dict(form=form))


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

main/web/templates/web/content/morouter.html
{% extends "web/base.html" %}
{% load static i18n %}
{% block title %}{% trans "MO Router" %}{% endblock title %}
{% block extracss %}{% endblock extracss %}
{% block content %}
<h1 class="h3 mb-2 text-gray-800">{% trans "MO Router" %}</h1>
<p><small class="muted-text">{% trans "MO is referred to Mobile Originated, a SMS-MO is an SMS sent from mobile" %}</small></p>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h4>
            <button class="btn btn-success btn-sm float-right" id="add_new_obj"><i class="fas fa-plus"></i> {% trans "Add New" %}</button>
        </h4>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover table-striped table-sm">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>{% trans "Type" %}</th>
                        <th>{% trans "Order" %}</th>
                        <th>{% trans "SMPP / HTTP Connectors" %}</th>
                        <th>{% trans "Fitlers" %}</th>
                        <th class="text-center">{% trans "Option" %}</th>
                    </tr>
                </thead>
                <tbody id="collectionlist"></tbody>
                <tbody class="isEmpty" style="display:none;">
                    <tr>
                        <td colspan="6" class="text-center"><i class="fas fa-cloud-upload-alt text-metal" style="font-size:5rem;"></i><br>{% trans "No MO Router" %}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="collection_modal" tabindex="-1" role="dialog" aria-labelledby="collection_modalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form id="add_modal_form" style="display:none" action="{% url 'web:morouter_view_manage' %}" method="post">{% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="collection_modalLabel">{% trans "Add New MO Router" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-info">
                        <small>- <strong>DefaultRoute</strong> a route without a filter, this one can only set with the lowest order to be a default/fallback route</small><br>
                        <small>- <strong>StaticMORoute</strong> a basic route with Filters and one Connector</small><br>
                        <small>- <strong>RandomRoundrobinMORoute</strong> a route with Filters and many Connectors, will return a random Connector if its Filters are matching, can be used as a load balancer route</small><br>
                        <small>- <strong>FailoverMORoute</strong> a route with Filters and many Connectors, will return an available (connected) Connector if its Filters are matched</small>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">{% trans "Type" %}</label>
                        <div class="col-sm-10">
                            <select name="type" class="form-control select">
                                {% for mo_router_type in mo_router_types %}
                                <option value="{{ mo_router_type.0 }}">{{ mo_router_type.1 }}</option>
                                {% endfor %}
                            </select>
                            <small class="text-muted">{% trans "One of the supported MO Routes: DefaultRoute, StaticMORoute, RandomRoundrobinMORoute and FailoverMORoute" %}</small>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">{% trans "Order" %}</label>
                        <div class="col-sm-10">
                            <input type="number" name="order" class="form-control" placeholder="{% trans 'Order' %}" required>
                            <small class="text-muted">{% trans "MO Route priority order, order must be unique and starts from 0" %}</small>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">{% trans "SMPP Connectors" %}</label>
                        <div class="col-sm-10">
                            <select name="smppconnectors" class="form-control" multiple></select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">{% trans "HTTP Connectors" %}</label>
                        <div class="col-sm-10">
                            <select name="httpconnectors" class="form-control" multiple></select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">{% trans "Filters" %}</label>
                        <div class="col-sm-10">
                            <select name="filters" class="form-control" multiple></select>
                            <small class="text-muted">{% trans "Always required except <b>DefaultRoute</b> option" %}</small>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Cancel" %}</button>
                    <button type="submit" class="btn btn-primary">{% trans "Add New MO Router" %}</button>
                </div>
                <input type="hidden" name="s" value="add">
            </form>
        </div>
    </div>
</div>
{% endblock content %}
{% block extrajs %}
<script>
var main_trans = {
    url2smppccm: "{% url 'web:smppccm_view_manage' %}",
    url2httpccm: "{% url 'web:httpccm_view_manage' %}",
    url2filters: "{% url 'web:filters_view_manage' %}",
};
</script>
<script src="{% static 'web/content/morouter.js' %}"></script>
{% endblock extrajs %}

main/web/templates/web/content/mtrouter.html
{% extends "web/base.html" %}
{% load static i18n %}
{% block title %}{% trans "MT Router" %}{% endblock title %}
{% block extracss %}{% endblock extracss %}
{% block content %}
<h1 class="h3 mb-2 text-gray-800">{% trans "MT Router" %}</h1>
<p><small class="muted-text">{% trans "MT is referred to Mobile Terminated, a SMS-MT is an SMS sent to mobile" %}</small></p>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h4>
            <button class="btn btn-success btn-sm float-right" id="add_new_obj"><i class="fas fa-plus"></i> {% trans "Add New" %}</button>
        </h4>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover table-striped table-sm">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>{% trans "Type" %}</th>
                        <th>{% trans "Order" %}</th>
                        <th>{% trans "Rate" %}</th>
                        <th>{% trans "SMPP / HTTP Connectors" %}</th>
                        <th>{% trans "Filters" %}</th>
                        <th class="text-center">{% trans "Option" %}</th>
                    </tr>
                </thead>
                <tbody id="collectionlist"></tbody>
                <tbody class="isEmpty" style="display:none;">
                    <tr>
                        <td colspan="7" class="text-center"><i class="fas fa-cloud-download-alt text-metal" style="font-size:5rem;"></i><br>{% trans "No MT Router" %}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="collection_modal" tabindex="-1" role="dialog" aria-labelledby="collection_modalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form id="add_modal_form" style="display:none" action="{% url 'web:mtrouter_view_manage' %}" method="post">{% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="collection_modalLabel">{% trans "Add New MT Router" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-info">
                        <small>- <strong>DefaultRoute</strong> a route without a filter, this one can only set with the lowest order to be a default/fallback route</small><br>
                        <small>- <strong>StaticMTRoute</strong> a basic route with Filters and one Connector</small><br>
                        <small>- <strong>RandomRoundrobinMTRoute</strong> a route with Filters and many Connectors, will return a random Connector if its Filters are matching, can be used as a load balancer route</small><br>
                        <small>- <strong>FailoverMTRoute</strong> a route with Filters and many Connectors, will return an available (connected) Connector if its Filters are matched</small>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">{% trans "Type" %}</label>
                        <div class="col-sm-10">
                            <select name="type" class="form-control select">
                                {% for mt_router_type in mt_router_types %}
                                    <option value="{{ mt_router_type.0 }}">{{ mt_router_type.1 }}</option>
                                {% endfor %}
                            </select>
                            <small class="text-muted">{% trans "One of the supported MT Routes: DefaultRoute, StaticMTRoute, RandomRoundrobinMTRoute and FailoverMTRoute" %}</small>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">{% trans "Order" %}</label>
                        <div class="col-sm-10">
                            <input type="number" name="order" class="form-control" placeholder="{% trans 'Order' %}" required>
                            <small class="text-muted">{% trans "MT Route priority order, order must be unique and starts from 0" %}</small>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">{% trans "Rate" %}</label>
                        <div class="col-sm-10">
                            <input type="number" name="rate" class="form-control" placeholder="{% trans 'Rate' %}">
                            <small class="text-muted">{% trans "The route rate, can be zero" %}</small>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">{% trans "SMPP Connectors" %}</label>
                        <div class="col-sm-10">
                            <select name="smppconnectors" class="form-control" multiple></select>
                            <small class="text-muted">{% trans "Only SMPP Connector allowed" %}</small>
                        </div>
                    </div>
                    <!-- <div class="form-group row">
                        <label class="col-sm-2 col-form-label">{% trans "HTTP Connectors" %}</label>
                        <div class="col-sm-10">
                            <select name="httpconnectors" class="form-control" multiple></select>
                        </div>
                    </div> -->
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">{% trans "Filters" %}</label>
                        <div class="col-sm-10">
                            <select name="filters" class="form-control" multiple></select>
                            <small class="text-muted">{% trans "Always required except <b>DefaultRoute</b> option" %}</small>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Cancel" %}</button>
                    <button type="submit" class="btn btn-primary">{% trans "Add New MT Router" %}</button>
                </div>
                <input type="hidden" name="s" value="add">
            </form>
        </div>
    </div>
</div>
{% endblock content %}
{% block extrajs %}
<script>
var main_trans = {
    url2smppccm: "{% url 'web:smppccm_view_manage' %}",
    url2httpccm: "{% url 'web:httpccm_view_manage' %}",
    url2filters: "{% url 'web:filters_view_manage' %}",
};
</script>
<script src="{% static 'web/content/mtrouter.js' %}"></script>
{% endblock extrajs %}