config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('jet/', include('jet.urls', namespace="jet")),
    path('jet/dashboard/', include('jet.dashboard.urls', namespace="jet-dashboard")),
    path(settings.ADMIN_URL, admin.site.urls),
    path('account/', include('main.users.urls', namespace="users")),
    path('api/', include('main.api.urls', namespace="api")),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('main.web.urls', namespace="web")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path(route='profile/', view=profile_view, name='profile_view'),
    path(route='settings/', view=settings_view, name='settings_view'),
    path(route='activity_log/', view=activity_log_view, name='activity_log_view'),
    path(route='login/', view=signin_view, name="signin_view"),
    path(route='logout/', view=logout_view, name="logout_view"),
    path(route='verify-email/<str:uidb64>/<str:token>/', view=email_verification_view, name='email_verification_view'),
    path(route='reset/<str:uidb64>/<str:token>/', view=reset_password_view, name="reset_password_view"),  # noqa
    path(route='reset/', view=reset_view, name="reset_view"),
]

main/web/urls.py
from django.urls import path

from main.web import views

app_name = 'web'

urlpatterns = [
    path('filters/manage/', views.filters_view_manage, name='filters_view_manage'),
    path('filters/', views.filters_view, name='filters_view'),
    path('groups/manage/', views.groups_view_manage, name='groups_view_manage'),
    path('groups/', views.groups_view, name='groups_view'),
    path('httpccm/manage/', views.httpccm_view_manage, name='httpccm_view_manage'),
    path('httpccm/', views.httpccm_view, name='httpccm_view'),
    path('morouter/manage/', views.morouter_view_manage, name='morouter_view_manage'),
    path('morouter/', views.morouter_view, name='morouter_view'),
    path('mtrouter/manage/', views.mtrouter_view_manage, name='mtrouter_view_manage'),
    path('mtrouter/', views.mtrouter_view, name='mtrouter_view'),
    path('smppccm/manage/', views.smppccm_view_manage, name='smppccm_view_manage'),
    path('smppccm/', views.smppccm_view, name='smppccm_view'),
    path('send_message/manage/', views.send_message_view_manage, name='send_message_view_manage'),
    path('send_message/', views.send_message_view, name='send_message_view'),
    path('submit_logs/export/', views.submit_logs_export, name='submit_logs_export'),
    path('submit_logs/export/progress/<str:task_id>/', views.submit_logs_export_progress, name='submit_logs_export_progress'),
    path('submit_logs/export/download/<str:task_id>/', views.submit_logs_export_download, name='submit_logs_export_download'),
    path('submit_logs/manage/', views.submit_logs_view_manage, name='submit_logs_view_manage'),
    path('submit_logs/', views.submit_logs_view, name='submit_logs_view'),
    path('users/manage/', views.users_view_manage, name='users_view_manage'),
    path('users/', views.users_view, name='users_view'),
    path('manage/', views.global_manage, name='global_manage'),
    path('', views.dashboard_view, name='dashboard_view'),
]

main/web/templates/web/includes/avatar_modal.html
{% load i18n %}
<div class="modal fade" id="avatar-modal" role="dialog" aria-labelledby="defModalHead" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form action="{% url 'users:profile_view' %}" method="POST" class="avatar-form" enctype="multipart/form-data">{% csrf_token %}
                <div class="modal-header">
                    <h4 class="modal-title" id="avatar-modal-label">{% trans "Change Avatar" %}</h4>
                </div>
                <div class="modal-body">
                    <div class="avatar-body">
                        <div class="avatar-upload">
                            <input type="hidden" class="avatar-src" name="avatar_src">
                            <input type="hidden" class="avatar-data" name="avatar_data">
                            <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                <span class="input-group-addon btn btn-default btn-file" style="border-right:#ddd 2px solid;">
                                <span class="fileinput-new">{% trans "Select File" %}</span>
                                <span class="fileinput-exists">{% trans "Change" %}</span>
                                <input type="file" class="avatar-input" id="avatarInput" name="avatar_file">
                                </span>
                                <div class="form-control1" data-trigger="fileinput">
                                    <i class="fa fa-file fileinput-exists"></i>
                                    <span class="fileinput-filename"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <div class="avatar-wrapper"></div>
                            </div>
                            <div class="col-md-4">
                                <div class="avatar-preview preview-lg"></div>
                            </div>
                        </div>
                        <div class="avatar-btns text-right">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-upload"></i>&nbsp;&nbsp;{% trans "Upload" %}</button>
                        </div>
                    </div>
                </div>
                <input type="hidden" name="s" value="avatar">
            </form>
        </div>
    </div>
</div>

main/web/templates/web/includes/footer.html
<footer class="sticky-footer bg-white">
    <div class="container-fluid my-auto">
        <div class="copyright my-auto">
            <span>Made with <i class="fas fa-heart text-danger"></i> Jasmin SMPP Server {% now 'Y' %}</span>
        </div>
    </div>
</footer>

main/web/templates/web/includes/message.html
{% load i18n %}
{% for message in messages %}
<div class="messages">
    <div class="alert alert-dismissable alert-{% if message.tags %}{{message.tags|lower}}{% endif %} fade show" role="alert">
        {{ message|safe }} <button type="button" class="close float-right" data-dismiss="alert">×</button>
    </div>
</div>
{% endfor %}

main/web/templates/web/includes/paginate.html
{% if page_obj.has_other_pages %}
<nav class="text-center" style="padding-bottom:10px;">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
        {% endif %}
    </ul>
</nav>
{% endif %}

main/web/templates/web/includes/paginate_ajax.html
{% load i18n %}
<div class="form-inline" style="display:none;">
	<ul class="pagination" id="pagenumbers"></ul>
	<div class="pagination-per-page">
		<select class="page-link" id="per_page">
			<option>10</option><option selected>20</option><option>50</option><option>100</option><option>1000</option><option>10000</option>
		</select> {% trans "Item per page" %}
	</div>
</div>

main/web/templates/web/includes/sidebar.html
{% load i18n %}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'web:dashboard_view' %}">
        <!--<div class="sidebar-brand-icon">
            <i class="fas fa-user-cog"></i>
        </div>-->
        <div class="sidebar-brand-text mx-2">{% trans 'Jasmin Panel' %} <sup>{{ VERSION }}</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    <li class="nav-item smppccm-menu">
        <a class="nav-link" href="{% url 'web:smppccm_view' %}"><i class="fas fa-fw fa-atom"></i><span>{% trans 'SMPPCCM' %}</span></a>
    </li>
    <li class="nav-item httpccm-menu">
        <a class="nav-link" href="{% url 'web:httpccm_view' %}"><i class="fas fa-fw fa-atom"></i><span>{% trans 'HTTPCCM' %}</span></a>
    </li>

    <hr class="sidebar-divider">

    <li class="nav-item users-menu">
        <a class="nav-link" href="{% url 'web:users_view' %}"><i class="fas fa-fw fa-user"></i><span>{% trans 'Users' %}</span></a>
    </li>

    <li class="nav-item groups-menu">
        <a class="nav-link" href="{% url 'web:groups_view' %}"><i class="fas fa-fw fa-users"></i><span>{% trans 'Groups' %}</span></a>
    </li>

    <hr class="sidebar-divider d-none d-md-block">

    <li class="nav-item filters-menu">
        <a class="nav-link" href="{% url 'web:filters_view' %}"><i class="fas fa-fw fa-filter"></i><span>{% trans 'Filters' %}</span></a>
    </li>

    <li class="nav-item mtrouter-menu">
        <a class="nav-link" href="{% url 'web:mtrouter_view' %}"><i class="fas fa-fw fa-cloud-download-alt"></i><span>{% trans 'MT Router' %}</span></a>
    </li>
    
    <li class="nav-item morouter-menu">
        <a class="nav-link" href="{% url 'web:morouter_view' %}"><i class="fas fa-fw fa-cloud-upload-alt"></i><span>{% trans 'MO Router' %}</span></a>
    </li>

    <hr class="sidebar-divider d-none d-md-block">

    <li class="nav-item send-sms-menu">
        <a class="nav-link" href="{% url 'web:send_message_view' %}"><i class="fas fa-fw fa-envelope"></i><span>{% trans 'Send SMS' %}</span></a>
    </li>

    {% if SETTINGS.SUBMIT_LOG %}
    <li class="nav-item submit_logs-menu">
        <a class="nav-link" href="{% url 'web:submit_logs_view' %}"><i class="fas fa-fw fa-clipboard-list"></i><span>{% trans 'Submit Logs' %}</span></a>
    </li>
    {% endif %}
</ul>

main/web/templates/web/includes/topbar.html
{% load i18n %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <div class="topbar-divider d-none d-sm-block"></div>
        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.get_full_name }}</span>
                <img class="img-profile rounded-circle" src="{{ request.user.img }}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'users:profile_view' %}">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    {% trans "Profile" %}
                </a>
                <a class="dropdown-item" href="{% url 'users:activity_log_view' %}">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    {% trans "Activity Log" %}
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'users:logout_view' %}">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    {% trans 'Logout' %}
                </a>
            </div>
        </li>
    </ul>
</nav>